import unittest
import src.flare_python_periphery_package as fpp


class TestCostonAbis(unittest.TestCase):
    def test_abis_exist_for_all_contracts(self):
        self.assertIsInstance(fpp.coston.abis.IWNat, list)
        self.assertIsInstance(fpp.coston.abis.IDelegationAccount, list)
        self.assertIsInstance(fpp.coston.abis.ICChainStake, list)
        self.assertIsInstance(fpp.coston.abis.IPriceSubmitter, list)
        self.assertIsInstance(fpp.coston.abis.IFastUpdateIncentiveManager, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoFeedIdConverter, list)
        self.assertIsInstance(fpp.coston.abis.ICChainVotePower, list)
        self.assertIsInstance(fpp.coston.abis.IRNatAccount, list)
        self.assertIsInstance(fpp.coston.abis.IEVMTransactionVerification, list)
        self.assertIsInstance(fpp.coston.abis.IFlareContractRegistry, list)
        self.assertIsInstance(fpp.coston.abis.IGovernanceSettings, list)
        self.assertIsInstance(fpp.coston.abis.IRandomProvider, list)
        self.assertIsInstance(fpp.coston.abis.IValidatorRewardOffersManager, list)
        self.assertIsInstance(fpp.coston.abis.EVMTransaction, list)
        self.assertIsInstance(fpp.coston.abis.IPaymentVerification, list)
        self.assertIsInstance(fpp.coston.abis.IVPToken, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoInflationConfigurations, list)
        self.assertIsInstance(fpp.coston.abis.IGovernanceVotePower, list)
        self.assertIsInstance(fpp.coston.abis.ISubmission, list)
        self.assertIsInstance(fpp.coston.abis.IBalanceDecreasingTransactionVerification, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoManager, list)
        self.assertIsInstance(fpp.coston.abis.IEntityManager, list)
        self.assertIsInstance(fpp.coston.abis.IPollingFtso, list)
        self.assertIsInstance(fpp.coston.abis.IFlareSystemsCalculator, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoFeedDecimals, list)
        self.assertIsInstance(fpp.coston.abis.IReferencedPaymentNonexistenceVerification, list)
        self.assertIsInstance(fpp.coston.abis.FlareContractsRegistryLibrary, list)
        self.assertIsInstance(fpp.coston.abis.BalanceDecreasingTransaction, list)
        self.assertIsInstance(fpp.coston.abis.IIncreaseManager, list)
        self.assertIsInstance(fpp.coston.abis.IMerkleRootStorage, list)
        self.assertIsInstance(fpp.coston.abis.IStateConnector, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoRewardOffersManager, list)
        self.assertIsInstance(fpp.coston.abis.IClaimSetupManager, list)
        self.assertIsInstance(fpp.coston.abis.IConfirmedBlockHeightExistsVerification, list)
        self.assertIsInstance(fpp.coston.abis.IAddressValidityVerification, list)
        self.assertIsInstance(fpp.coston.abis.ReferencedPaymentNonexistence, list)
        self.assertIsInstance(fpp.coston.abis.IFastUpdatesConfiguration, list)
        self.assertIsInstance(fpp.coston.abis.IGenericRewardManager, list)
        self.assertIsInstance(fpp.coston.abis.IFlareSystemsManager, list)
        self.assertIsInstance(fpp.coston.abis.IFlareAssetRegistry, list)
        self.assertIsInstance(fpp.coston.abis.IGovernor, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoRewardManager, list)
        self.assertIsInstance(fpp.coston.abis.IVoterRegistry, list)
        self.assertIsInstance(fpp.coston.abis.AddressValidity, list)
        self.assertIsInstance(fpp.coston.abis.IWNatDelegationFee, list)
        self.assertIsInstance(fpp.coston.abis.Payment, list)
        self.assertIsInstance(fpp.coston.abis.IVoterWhitelister, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoFeedPublisher, list)
        self.assertIsInstance(fpp.coston.abis.IRelay, list)
        self.assertIsInstance(fpp.coston.abis.IRewardManager, list)
        self.assertIsInstance(fpp.coston.abis.IFastUpdater, list)
        self.assertIsInstance(fpp.coston.abis.IRNat, list)
        self.assertIsInstance(fpp.coston.abis.IVPContractEvents, list)
        self.assertIsInstance(fpp.coston.abis.IFtso, list)
        self.assertIsInstance(fpp.coston.abis.ConfirmedBlockHeightExists, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoRegistry, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoGenesis, list)
        self.assertIsInstance(fpp.coston.abis.IFlareDaemonize, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoRegistryGenesis, list)
        self.assertIsInstance(fpp.coston.abis.IFtsoManagerGenesis, list)
        self.assertIsInstance(fpp.coston.abis.IIEntityManager, list)
        self.assertIsInstance(fpp.coston.abis.IICleanupBlockNumberManager, list)
        self.assertIsInstance(fpp.coston.abis.IIRewardManager, list)
        self.assertIsInstance(fpp.coston.abis.IIVoterRegistry, list)
        self.assertIsInstance(fpp.coston.abis.IIPublicKeyVerifier, list)
        self.assertIsInstance(fpp.coston.abis.IISubmission, list)
        self.assertIsInstance(fpp.coston.abis.IIVoterRegistrationTrigger, list)
        self.assertIsInstance(fpp.coston.abis.IIClaimSetupManager, list)
        self.assertIsInstance(fpp.coston.abis.IIRelay, list)
        self.assertIsInstance(fpp.coston.abis.IIRewardEpochSwitchoverTrigger, list)
        self.assertIsInstance(fpp.coston.abis.IIFlareSystemsCalculator, list)
        self.assertIsInstance(fpp.coston.abis.IINodePossessionVerifier, list)
        self.assertIsInstance(fpp.coston.abis.IIFlareSystemsManager, list)
        self.assertIsInstance(fpp.coston.abis.IICleanable, list)
        self.assertIsInstance(fpp.coston.abis.IIVPToken, list)
        self.assertIsInstance(fpp.coston.abis.IIVPContract, list)
        self.assertIsInstance(fpp.coston.abis.IIGovernanceVotePower, list)
        self.assertIsInstance(fpp.coston.abis.IIRNatAccount, list)
        self.assertIsInstance(fpp.coston.abis.IIRNat, list)
        self.assertIsInstance(fpp.coston.abis.IIFtsoFeedPublisher, list)
        self.assertIsInstance(fpp.coston.abis.IIFtso, list)
        self.assertIsInstance(fpp.coston.abis.IIPollingFoundation, list)
        self.assertIsInstance(fpp.coston.abis.IIGovernorProposer, list)
        self.assertIsInstance(fpp.coston.abis.Bn256, list)
        self.assertIsInstance(fpp.coston.abis.IIFastUpdater, list)
        self.assertIsInstance(fpp.coston.abis.IIFastUpdateIncentiveManager, list)

    def test_name_to_abi(self):
        self.assertIsInstance(fpp.coston.name_to_abi("IWNat"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IDelegationAccount"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("ICChainStake"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IPriceSubmitter"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFastUpdateIncentiveManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoFeedIdConverter"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("ICChainVotePower"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IRNatAccount"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IEVMTransactionVerification"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFlareContractRegistry"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IGovernanceSettings"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IRandomProvider"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IValidatorRewardOffersManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("EVMTransaction"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IPaymentVerification"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IVPToken"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoInflationConfigurations"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IGovernanceVotePower"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("ISubmission"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IBalanceDecreasingTransactionVerification"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IEntityManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IPollingFtso"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFlareSystemsCalculator"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoFeedDecimals"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IReferencedPaymentNonexistenceVerification"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("FlareContractsRegistryLibrary"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("BalanceDecreasingTransaction"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIncreaseManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IMerkleRootStorage"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IStateConnector"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoRewardOffersManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IClaimSetupManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IConfirmedBlockHeightExistsVerification"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IAddressValidityVerification"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("ReferencedPaymentNonexistence"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFastUpdatesConfiguration"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IGenericRewardManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFlareSystemsManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFlareAssetRegistry"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IGovernor"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoRewardManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IVoterRegistry"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("AddressValidity"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IWNatDelegationFee"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("Payment"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IVoterWhitelister"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoFeedPublisher"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IRelay"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IRewardManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFastUpdater"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IRNat"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IVPContractEvents"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtso"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("ConfirmedBlockHeightExists"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoRegistry"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoGenesis"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFlareDaemonize"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoRegistryGenesis"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IFtsoManagerGenesis"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIEntityManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IICleanupBlockNumberManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIRewardManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIVoterRegistry"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIPublicKeyVerifier"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IISubmission"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIVoterRegistrationTrigger"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIClaimSetupManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIRelay"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIRewardEpochSwitchoverTrigger"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIFlareSystemsCalculator"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IINodePossessionVerifier"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIFlareSystemsManager"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IICleanable"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIVPToken"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIVPContract"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIGovernanceVotePower"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIRNatAccount"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIRNat"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIFtsoFeedPublisher"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIFtso"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIPollingFoundation"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIGovernorProposer"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("Bn256"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIFastUpdater"), list)
        self.assertIsInstance(fpp.coston.name_to_abi("IIFastUpdateIncentiveManager"), list)

    def test_abis_are_copied(self):
        self.assertEqual(fpp.coston.abis.IWNat, fpp.coston.name_to_abi("IWNat"))
        self.assertIsNot(fpp.coston.abis.IWNat, fpp.coston.name_to_abi("IWNat"))
        for el1, el2 in zip(fpp.coston.abis.IWNat, fpp.coston.name_to_abi("IWNat")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IDelegationAccount, fpp.coston.name_to_abi("IDelegationAccount"))
        self.assertIsNot(fpp.coston.abis.IDelegationAccount, fpp.coston.name_to_abi("IDelegationAccount"))
        for el1, el2 in zip(fpp.coston.abis.IDelegationAccount, fpp.coston.name_to_abi("IDelegationAccount")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.ICChainStake, fpp.coston.name_to_abi("ICChainStake"))
        self.assertIsNot(fpp.coston.abis.ICChainStake, fpp.coston.name_to_abi("ICChainStake"))
        for el1, el2 in zip(fpp.coston.abis.ICChainStake, fpp.coston.name_to_abi("ICChainStake")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IPriceSubmitter, fpp.coston.name_to_abi("IPriceSubmitter"))
        self.assertIsNot(fpp.coston.abis.IPriceSubmitter, fpp.coston.name_to_abi("IPriceSubmitter"))
        for el1, el2 in zip(fpp.coston.abis.IPriceSubmitter, fpp.coston.name_to_abi("IPriceSubmitter")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFastUpdateIncentiveManager, fpp.coston.name_to_abi("IFastUpdateIncentiveManager"))
        self.assertIsNot(fpp.coston.abis.IFastUpdateIncentiveManager, fpp.coston.name_to_abi("IFastUpdateIncentiveManager"))
        for el1, el2 in zip(fpp.coston.abis.IFastUpdateIncentiveManager, fpp.coston.name_to_abi("IFastUpdateIncentiveManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoFeedIdConverter, fpp.coston.name_to_abi("IFtsoFeedIdConverter"))
        self.assertIsNot(fpp.coston.abis.IFtsoFeedIdConverter, fpp.coston.name_to_abi("IFtsoFeedIdConverter"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoFeedIdConverter, fpp.coston.name_to_abi("IFtsoFeedIdConverter")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.ICChainVotePower, fpp.coston.name_to_abi("ICChainVotePower"))
        self.assertIsNot(fpp.coston.abis.ICChainVotePower, fpp.coston.name_to_abi("ICChainVotePower"))
        for el1, el2 in zip(fpp.coston.abis.ICChainVotePower, fpp.coston.name_to_abi("ICChainVotePower")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IRNatAccount, fpp.coston.name_to_abi("IRNatAccount"))
        self.assertIsNot(fpp.coston.abis.IRNatAccount, fpp.coston.name_to_abi("IRNatAccount"))
        for el1, el2 in zip(fpp.coston.abis.IRNatAccount, fpp.coston.name_to_abi("IRNatAccount")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IEVMTransactionVerification, fpp.coston.name_to_abi("IEVMTransactionVerification"))
        self.assertIsNot(fpp.coston.abis.IEVMTransactionVerification, fpp.coston.name_to_abi("IEVMTransactionVerification"))
        for el1, el2 in zip(fpp.coston.abis.IEVMTransactionVerification, fpp.coston.name_to_abi("IEVMTransactionVerification")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFlareContractRegistry, fpp.coston.name_to_abi("IFlareContractRegistry"))
        self.assertIsNot(fpp.coston.abis.IFlareContractRegistry, fpp.coston.name_to_abi("IFlareContractRegistry"))
        for el1, el2 in zip(fpp.coston.abis.IFlareContractRegistry, fpp.coston.name_to_abi("IFlareContractRegistry")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IGovernanceSettings, fpp.coston.name_to_abi("IGovernanceSettings"))
        self.assertIsNot(fpp.coston.abis.IGovernanceSettings, fpp.coston.name_to_abi("IGovernanceSettings"))
        for el1, el2 in zip(fpp.coston.abis.IGovernanceSettings, fpp.coston.name_to_abi("IGovernanceSettings")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IRandomProvider, fpp.coston.name_to_abi("IRandomProvider"))
        self.assertIsNot(fpp.coston.abis.IRandomProvider, fpp.coston.name_to_abi("IRandomProvider"))
        for el1, el2 in zip(fpp.coston.abis.IRandomProvider, fpp.coston.name_to_abi("IRandomProvider")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IValidatorRewardOffersManager, fpp.coston.name_to_abi("IValidatorRewardOffersManager"))
        self.assertIsNot(fpp.coston.abis.IValidatorRewardOffersManager, fpp.coston.name_to_abi("IValidatorRewardOffersManager"))
        for el1, el2 in zip(fpp.coston.abis.IValidatorRewardOffersManager, fpp.coston.name_to_abi("IValidatorRewardOffersManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.EVMTransaction, fpp.coston.name_to_abi("EVMTransaction"))
        self.assertIsNot(fpp.coston.abis.EVMTransaction, fpp.coston.name_to_abi("EVMTransaction"))
        for el1, el2 in zip(fpp.coston.abis.EVMTransaction, fpp.coston.name_to_abi("EVMTransaction")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IPaymentVerification, fpp.coston.name_to_abi("IPaymentVerification"))
        self.assertIsNot(fpp.coston.abis.IPaymentVerification, fpp.coston.name_to_abi("IPaymentVerification"))
        for el1, el2 in zip(fpp.coston.abis.IPaymentVerification, fpp.coston.name_to_abi("IPaymentVerification")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IVPToken, fpp.coston.name_to_abi("IVPToken"))
        self.assertIsNot(fpp.coston.abis.IVPToken, fpp.coston.name_to_abi("IVPToken"))
        for el1, el2 in zip(fpp.coston.abis.IVPToken, fpp.coston.name_to_abi("IVPToken")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoInflationConfigurations, fpp.coston.name_to_abi("IFtsoInflationConfigurations"))
        self.assertIsNot(fpp.coston.abis.IFtsoInflationConfigurations, fpp.coston.name_to_abi("IFtsoInflationConfigurations"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoInflationConfigurations, fpp.coston.name_to_abi("IFtsoInflationConfigurations")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IGovernanceVotePower, fpp.coston.name_to_abi("IGovernanceVotePower"))
        self.assertIsNot(fpp.coston.abis.IGovernanceVotePower, fpp.coston.name_to_abi("IGovernanceVotePower"))
        for el1, el2 in zip(fpp.coston.abis.IGovernanceVotePower, fpp.coston.name_to_abi("IGovernanceVotePower")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.ISubmission, fpp.coston.name_to_abi("ISubmission"))
        self.assertIsNot(fpp.coston.abis.ISubmission, fpp.coston.name_to_abi("ISubmission"))
        for el1, el2 in zip(fpp.coston.abis.ISubmission, fpp.coston.name_to_abi("ISubmission")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IBalanceDecreasingTransactionVerification, fpp.coston.name_to_abi("IBalanceDecreasingTransactionVerification"))
        self.assertIsNot(fpp.coston.abis.IBalanceDecreasingTransactionVerification, fpp.coston.name_to_abi("IBalanceDecreasingTransactionVerification"))
        for el1, el2 in zip(fpp.coston.abis.IBalanceDecreasingTransactionVerification, fpp.coston.name_to_abi("IBalanceDecreasingTransactionVerification")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoManager, fpp.coston.name_to_abi("IFtsoManager"))
        self.assertIsNot(fpp.coston.abis.IFtsoManager, fpp.coston.name_to_abi("IFtsoManager"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoManager, fpp.coston.name_to_abi("IFtsoManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IEntityManager, fpp.coston.name_to_abi("IEntityManager"))
        self.assertIsNot(fpp.coston.abis.IEntityManager, fpp.coston.name_to_abi("IEntityManager"))
        for el1, el2 in zip(fpp.coston.abis.IEntityManager, fpp.coston.name_to_abi("IEntityManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IPollingFtso, fpp.coston.name_to_abi("IPollingFtso"))
        self.assertIsNot(fpp.coston.abis.IPollingFtso, fpp.coston.name_to_abi("IPollingFtso"))
        for el1, el2 in zip(fpp.coston.abis.IPollingFtso, fpp.coston.name_to_abi("IPollingFtso")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFlareSystemsCalculator, fpp.coston.name_to_abi("IFlareSystemsCalculator"))
        self.assertIsNot(fpp.coston.abis.IFlareSystemsCalculator, fpp.coston.name_to_abi("IFlareSystemsCalculator"))
        for el1, el2 in zip(fpp.coston.abis.IFlareSystemsCalculator, fpp.coston.name_to_abi("IFlareSystemsCalculator")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoFeedDecimals, fpp.coston.name_to_abi("IFtsoFeedDecimals"))
        self.assertIsNot(fpp.coston.abis.IFtsoFeedDecimals, fpp.coston.name_to_abi("IFtsoFeedDecimals"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoFeedDecimals, fpp.coston.name_to_abi("IFtsoFeedDecimals")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IReferencedPaymentNonexistenceVerification, fpp.coston.name_to_abi("IReferencedPaymentNonexistenceVerification"))
        self.assertIsNot(fpp.coston.abis.IReferencedPaymentNonexistenceVerification, fpp.coston.name_to_abi("IReferencedPaymentNonexistenceVerification"))
        for el1, el2 in zip(fpp.coston.abis.IReferencedPaymentNonexistenceVerification, fpp.coston.name_to_abi("IReferencedPaymentNonexistenceVerification")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.FlareContractsRegistryLibrary, fpp.coston.name_to_abi("FlareContractsRegistryLibrary"))
        self.assertIsNot(fpp.coston.abis.FlareContractsRegistryLibrary, fpp.coston.name_to_abi("FlareContractsRegistryLibrary"))
        for el1, el2 in zip(fpp.coston.abis.FlareContractsRegistryLibrary, fpp.coston.name_to_abi("FlareContractsRegistryLibrary")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.BalanceDecreasingTransaction, fpp.coston.name_to_abi("BalanceDecreasingTransaction"))
        self.assertIsNot(fpp.coston.abis.BalanceDecreasingTransaction, fpp.coston.name_to_abi("BalanceDecreasingTransaction"))
        for el1, el2 in zip(fpp.coston.abis.BalanceDecreasingTransaction, fpp.coston.name_to_abi("BalanceDecreasingTransaction")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIncreaseManager, fpp.coston.name_to_abi("IIncreaseManager"))
        self.assertIsNot(fpp.coston.abis.IIncreaseManager, fpp.coston.name_to_abi("IIncreaseManager"))
        for el1, el2 in zip(fpp.coston.abis.IIncreaseManager, fpp.coston.name_to_abi("IIncreaseManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IMerkleRootStorage, fpp.coston.name_to_abi("IMerkleRootStorage"))
        self.assertIsNot(fpp.coston.abis.IMerkleRootStorage, fpp.coston.name_to_abi("IMerkleRootStorage"))
        for el1, el2 in zip(fpp.coston.abis.IMerkleRootStorage, fpp.coston.name_to_abi("IMerkleRootStorage")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IStateConnector, fpp.coston.name_to_abi("IStateConnector"))
        self.assertIsNot(fpp.coston.abis.IStateConnector, fpp.coston.name_to_abi("IStateConnector"))
        for el1, el2 in zip(fpp.coston.abis.IStateConnector, fpp.coston.name_to_abi("IStateConnector")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoRewardOffersManager, fpp.coston.name_to_abi("IFtsoRewardOffersManager"))
        self.assertIsNot(fpp.coston.abis.IFtsoRewardOffersManager, fpp.coston.name_to_abi("IFtsoRewardOffersManager"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoRewardOffersManager, fpp.coston.name_to_abi("IFtsoRewardOffersManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IClaimSetupManager, fpp.coston.name_to_abi("IClaimSetupManager"))
        self.assertIsNot(fpp.coston.abis.IClaimSetupManager, fpp.coston.name_to_abi("IClaimSetupManager"))
        for el1, el2 in zip(fpp.coston.abis.IClaimSetupManager, fpp.coston.name_to_abi("IClaimSetupManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IConfirmedBlockHeightExistsVerification, fpp.coston.name_to_abi("IConfirmedBlockHeightExistsVerification"))
        self.assertIsNot(fpp.coston.abis.IConfirmedBlockHeightExistsVerification, fpp.coston.name_to_abi("IConfirmedBlockHeightExistsVerification"))
        for el1, el2 in zip(fpp.coston.abis.IConfirmedBlockHeightExistsVerification, fpp.coston.name_to_abi("IConfirmedBlockHeightExistsVerification")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IAddressValidityVerification, fpp.coston.name_to_abi("IAddressValidityVerification"))
        self.assertIsNot(fpp.coston.abis.IAddressValidityVerification, fpp.coston.name_to_abi("IAddressValidityVerification"))
        for el1, el2 in zip(fpp.coston.abis.IAddressValidityVerification, fpp.coston.name_to_abi("IAddressValidityVerification")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.ReferencedPaymentNonexistence, fpp.coston.name_to_abi("ReferencedPaymentNonexistence"))
        self.assertIsNot(fpp.coston.abis.ReferencedPaymentNonexistence, fpp.coston.name_to_abi("ReferencedPaymentNonexistence"))
        for el1, el2 in zip(fpp.coston.abis.ReferencedPaymentNonexistence, fpp.coston.name_to_abi("ReferencedPaymentNonexistence")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFastUpdatesConfiguration, fpp.coston.name_to_abi("IFastUpdatesConfiguration"))
        self.assertIsNot(fpp.coston.abis.IFastUpdatesConfiguration, fpp.coston.name_to_abi("IFastUpdatesConfiguration"))
        for el1, el2 in zip(fpp.coston.abis.IFastUpdatesConfiguration, fpp.coston.name_to_abi("IFastUpdatesConfiguration")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IGenericRewardManager, fpp.coston.name_to_abi("IGenericRewardManager"))
        self.assertIsNot(fpp.coston.abis.IGenericRewardManager, fpp.coston.name_to_abi("IGenericRewardManager"))
        for el1, el2 in zip(fpp.coston.abis.IGenericRewardManager, fpp.coston.name_to_abi("IGenericRewardManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFlareSystemsManager, fpp.coston.name_to_abi("IFlareSystemsManager"))
        self.assertIsNot(fpp.coston.abis.IFlareSystemsManager, fpp.coston.name_to_abi("IFlareSystemsManager"))
        for el1, el2 in zip(fpp.coston.abis.IFlareSystemsManager, fpp.coston.name_to_abi("IFlareSystemsManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFlareAssetRegistry, fpp.coston.name_to_abi("IFlareAssetRegistry"))
        self.assertIsNot(fpp.coston.abis.IFlareAssetRegistry, fpp.coston.name_to_abi("IFlareAssetRegistry"))
        for el1, el2 in zip(fpp.coston.abis.IFlareAssetRegistry, fpp.coston.name_to_abi("IFlareAssetRegistry")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IGovernor, fpp.coston.name_to_abi("IGovernor"))
        self.assertIsNot(fpp.coston.abis.IGovernor, fpp.coston.name_to_abi("IGovernor"))
        for el1, el2 in zip(fpp.coston.abis.IGovernor, fpp.coston.name_to_abi("IGovernor")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoRewardManager, fpp.coston.name_to_abi("IFtsoRewardManager"))
        self.assertIsNot(fpp.coston.abis.IFtsoRewardManager, fpp.coston.name_to_abi("IFtsoRewardManager"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoRewardManager, fpp.coston.name_to_abi("IFtsoRewardManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IVoterRegistry, fpp.coston.name_to_abi("IVoterRegistry"))
        self.assertIsNot(fpp.coston.abis.IVoterRegistry, fpp.coston.name_to_abi("IVoterRegistry"))
        for el1, el2 in zip(fpp.coston.abis.IVoterRegistry, fpp.coston.name_to_abi("IVoterRegistry")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.AddressValidity, fpp.coston.name_to_abi("AddressValidity"))
        self.assertIsNot(fpp.coston.abis.AddressValidity, fpp.coston.name_to_abi("AddressValidity"))
        for el1, el2 in zip(fpp.coston.abis.AddressValidity, fpp.coston.name_to_abi("AddressValidity")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IWNatDelegationFee, fpp.coston.name_to_abi("IWNatDelegationFee"))
        self.assertIsNot(fpp.coston.abis.IWNatDelegationFee, fpp.coston.name_to_abi("IWNatDelegationFee"))
        for el1, el2 in zip(fpp.coston.abis.IWNatDelegationFee, fpp.coston.name_to_abi("IWNatDelegationFee")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.Payment, fpp.coston.name_to_abi("Payment"))
        self.assertIsNot(fpp.coston.abis.Payment, fpp.coston.name_to_abi("Payment"))
        for el1, el2 in zip(fpp.coston.abis.Payment, fpp.coston.name_to_abi("Payment")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IVoterWhitelister, fpp.coston.name_to_abi("IVoterWhitelister"))
        self.assertIsNot(fpp.coston.abis.IVoterWhitelister, fpp.coston.name_to_abi("IVoterWhitelister"))
        for el1, el2 in zip(fpp.coston.abis.IVoterWhitelister, fpp.coston.name_to_abi("IVoterWhitelister")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoFeedPublisher, fpp.coston.name_to_abi("IFtsoFeedPublisher"))
        self.assertIsNot(fpp.coston.abis.IFtsoFeedPublisher, fpp.coston.name_to_abi("IFtsoFeedPublisher"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoFeedPublisher, fpp.coston.name_to_abi("IFtsoFeedPublisher")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IRelay, fpp.coston.name_to_abi("IRelay"))
        self.assertIsNot(fpp.coston.abis.IRelay, fpp.coston.name_to_abi("IRelay"))
        for el1, el2 in zip(fpp.coston.abis.IRelay, fpp.coston.name_to_abi("IRelay")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IRewardManager, fpp.coston.name_to_abi("IRewardManager"))
        self.assertIsNot(fpp.coston.abis.IRewardManager, fpp.coston.name_to_abi("IRewardManager"))
        for el1, el2 in zip(fpp.coston.abis.IRewardManager, fpp.coston.name_to_abi("IRewardManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFastUpdater, fpp.coston.name_to_abi("IFastUpdater"))
        self.assertIsNot(fpp.coston.abis.IFastUpdater, fpp.coston.name_to_abi("IFastUpdater"))
        for el1, el2 in zip(fpp.coston.abis.IFastUpdater, fpp.coston.name_to_abi("IFastUpdater")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IRNat, fpp.coston.name_to_abi("IRNat"))
        self.assertIsNot(fpp.coston.abis.IRNat, fpp.coston.name_to_abi("IRNat"))
        for el1, el2 in zip(fpp.coston.abis.IRNat, fpp.coston.name_to_abi("IRNat")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IVPContractEvents, fpp.coston.name_to_abi("IVPContractEvents"))
        self.assertIsNot(fpp.coston.abis.IVPContractEvents, fpp.coston.name_to_abi("IVPContractEvents"))
        for el1, el2 in zip(fpp.coston.abis.IVPContractEvents, fpp.coston.name_to_abi("IVPContractEvents")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtso, fpp.coston.name_to_abi("IFtso"))
        self.assertIsNot(fpp.coston.abis.IFtso, fpp.coston.name_to_abi("IFtso"))
        for el1, el2 in zip(fpp.coston.abis.IFtso, fpp.coston.name_to_abi("IFtso")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.ConfirmedBlockHeightExists, fpp.coston.name_to_abi("ConfirmedBlockHeightExists"))
        self.assertIsNot(fpp.coston.abis.ConfirmedBlockHeightExists, fpp.coston.name_to_abi("ConfirmedBlockHeightExists"))
        for el1, el2 in zip(fpp.coston.abis.ConfirmedBlockHeightExists, fpp.coston.name_to_abi("ConfirmedBlockHeightExists")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoRegistry, fpp.coston.name_to_abi("IFtsoRegistry"))
        self.assertIsNot(fpp.coston.abis.IFtsoRegistry, fpp.coston.name_to_abi("IFtsoRegistry"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoRegistry, fpp.coston.name_to_abi("IFtsoRegistry")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoGenesis, fpp.coston.name_to_abi("IFtsoGenesis"))
        self.assertIsNot(fpp.coston.abis.IFtsoGenesis, fpp.coston.name_to_abi("IFtsoGenesis"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoGenesis, fpp.coston.name_to_abi("IFtsoGenesis")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFlareDaemonize, fpp.coston.name_to_abi("IFlareDaemonize"))
        self.assertIsNot(fpp.coston.abis.IFlareDaemonize, fpp.coston.name_to_abi("IFlareDaemonize"))
        for el1, el2 in zip(fpp.coston.abis.IFlareDaemonize, fpp.coston.name_to_abi("IFlareDaemonize")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoRegistryGenesis, fpp.coston.name_to_abi("IFtsoRegistryGenesis"))
        self.assertIsNot(fpp.coston.abis.IFtsoRegistryGenesis, fpp.coston.name_to_abi("IFtsoRegistryGenesis"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoRegistryGenesis, fpp.coston.name_to_abi("IFtsoRegistryGenesis")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IFtsoManagerGenesis, fpp.coston.name_to_abi("IFtsoManagerGenesis"))
        self.assertIsNot(fpp.coston.abis.IFtsoManagerGenesis, fpp.coston.name_to_abi("IFtsoManagerGenesis"))
        for el1, el2 in zip(fpp.coston.abis.IFtsoManagerGenesis, fpp.coston.name_to_abi("IFtsoManagerGenesis")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIEntityManager, fpp.coston.name_to_abi("IIEntityManager"))
        self.assertIsNot(fpp.coston.abis.IIEntityManager, fpp.coston.name_to_abi("IIEntityManager"))
        for el1, el2 in zip(fpp.coston.abis.IIEntityManager, fpp.coston.name_to_abi("IIEntityManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IICleanupBlockNumberManager, fpp.coston.name_to_abi("IICleanupBlockNumberManager"))
        self.assertIsNot(fpp.coston.abis.IICleanupBlockNumberManager, fpp.coston.name_to_abi("IICleanupBlockNumberManager"))
        for el1, el2 in zip(fpp.coston.abis.IICleanupBlockNumberManager, fpp.coston.name_to_abi("IICleanupBlockNumberManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIRewardManager, fpp.coston.name_to_abi("IIRewardManager"))
        self.assertIsNot(fpp.coston.abis.IIRewardManager, fpp.coston.name_to_abi("IIRewardManager"))
        for el1, el2 in zip(fpp.coston.abis.IIRewardManager, fpp.coston.name_to_abi("IIRewardManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIVoterRegistry, fpp.coston.name_to_abi("IIVoterRegistry"))
        self.assertIsNot(fpp.coston.abis.IIVoterRegistry, fpp.coston.name_to_abi("IIVoterRegistry"))
        for el1, el2 in zip(fpp.coston.abis.IIVoterRegistry, fpp.coston.name_to_abi("IIVoterRegistry")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIPublicKeyVerifier, fpp.coston.name_to_abi("IIPublicKeyVerifier"))
        self.assertIsNot(fpp.coston.abis.IIPublicKeyVerifier, fpp.coston.name_to_abi("IIPublicKeyVerifier"))
        for el1, el2 in zip(fpp.coston.abis.IIPublicKeyVerifier, fpp.coston.name_to_abi("IIPublicKeyVerifier")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IISubmission, fpp.coston.name_to_abi("IISubmission"))
        self.assertIsNot(fpp.coston.abis.IISubmission, fpp.coston.name_to_abi("IISubmission"))
        for el1, el2 in zip(fpp.coston.abis.IISubmission, fpp.coston.name_to_abi("IISubmission")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIVoterRegistrationTrigger, fpp.coston.name_to_abi("IIVoterRegistrationTrigger"))
        self.assertIsNot(fpp.coston.abis.IIVoterRegistrationTrigger, fpp.coston.name_to_abi("IIVoterRegistrationTrigger"))
        for el1, el2 in zip(fpp.coston.abis.IIVoterRegistrationTrigger, fpp.coston.name_to_abi("IIVoterRegistrationTrigger")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIClaimSetupManager, fpp.coston.name_to_abi("IIClaimSetupManager"))
        self.assertIsNot(fpp.coston.abis.IIClaimSetupManager, fpp.coston.name_to_abi("IIClaimSetupManager"))
        for el1, el2 in zip(fpp.coston.abis.IIClaimSetupManager, fpp.coston.name_to_abi("IIClaimSetupManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIRelay, fpp.coston.name_to_abi("IIRelay"))
        self.assertIsNot(fpp.coston.abis.IIRelay, fpp.coston.name_to_abi("IIRelay"))
        for el1, el2 in zip(fpp.coston.abis.IIRelay, fpp.coston.name_to_abi("IIRelay")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIRewardEpochSwitchoverTrigger, fpp.coston.name_to_abi("IIRewardEpochSwitchoverTrigger"))
        self.assertIsNot(fpp.coston.abis.IIRewardEpochSwitchoverTrigger, fpp.coston.name_to_abi("IIRewardEpochSwitchoverTrigger"))
        for el1, el2 in zip(fpp.coston.abis.IIRewardEpochSwitchoverTrigger, fpp.coston.name_to_abi("IIRewardEpochSwitchoverTrigger")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIFlareSystemsCalculator, fpp.coston.name_to_abi("IIFlareSystemsCalculator"))
        self.assertIsNot(fpp.coston.abis.IIFlareSystemsCalculator, fpp.coston.name_to_abi("IIFlareSystemsCalculator"))
        for el1, el2 in zip(fpp.coston.abis.IIFlareSystemsCalculator, fpp.coston.name_to_abi("IIFlareSystemsCalculator")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IINodePossessionVerifier, fpp.coston.name_to_abi("IINodePossessionVerifier"))
        self.assertIsNot(fpp.coston.abis.IINodePossessionVerifier, fpp.coston.name_to_abi("IINodePossessionVerifier"))
        for el1, el2 in zip(fpp.coston.abis.IINodePossessionVerifier, fpp.coston.name_to_abi("IINodePossessionVerifier")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIFlareSystemsManager, fpp.coston.name_to_abi("IIFlareSystemsManager"))
        self.assertIsNot(fpp.coston.abis.IIFlareSystemsManager, fpp.coston.name_to_abi("IIFlareSystemsManager"))
        for el1, el2 in zip(fpp.coston.abis.IIFlareSystemsManager, fpp.coston.name_to_abi("IIFlareSystemsManager")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IICleanable, fpp.coston.name_to_abi("IICleanable"))
        self.assertIsNot(fpp.coston.abis.IICleanable, fpp.coston.name_to_abi("IICleanable"))
        for el1, el2 in zip(fpp.coston.abis.IICleanable, fpp.coston.name_to_abi("IICleanable")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIVPToken, fpp.coston.name_to_abi("IIVPToken"))
        self.assertIsNot(fpp.coston.abis.IIVPToken, fpp.coston.name_to_abi("IIVPToken"))
        for el1, el2 in zip(fpp.coston.abis.IIVPToken, fpp.coston.name_to_abi("IIVPToken")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIVPContract, fpp.coston.name_to_abi("IIVPContract"))
        self.assertIsNot(fpp.coston.abis.IIVPContract, fpp.coston.name_to_abi("IIVPContract"))
        for el1, el2 in zip(fpp.coston.abis.IIVPContract, fpp.coston.name_to_abi("IIVPContract")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIGovernanceVotePower, fpp.coston.name_to_abi("IIGovernanceVotePower"))
        self.assertIsNot(fpp.coston.abis.IIGovernanceVotePower, fpp.coston.name_to_abi("IIGovernanceVotePower"))
        for el1, el2 in zip(fpp.coston.abis.IIGovernanceVotePower, fpp.coston.name_to_abi("IIGovernanceVotePower")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIRNatAccount, fpp.coston.name_to_abi("IIRNatAccount"))
        self.assertIsNot(fpp.coston.abis.IIRNatAccount, fpp.coston.name_to_abi("IIRNatAccount"))
        for el1, el2 in zip(fpp.coston.abis.IIRNatAccount, fpp.coston.name_to_abi("IIRNatAccount")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIRNat, fpp.coston.name_to_abi("IIRNat"))
        self.assertIsNot(fpp.coston.abis.IIRNat, fpp.coston.name_to_abi("IIRNat"))
        for el1, el2 in zip(fpp.coston.abis.IIRNat, fpp.coston.name_to_abi("IIRNat")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIFtsoFeedPublisher, fpp.coston.name_to_abi("IIFtsoFeedPublisher"))
        self.assertIsNot(fpp.coston.abis.IIFtsoFeedPublisher, fpp.coston.name_to_abi("IIFtsoFeedPublisher"))
        for el1, el2 in zip(fpp.coston.abis.IIFtsoFeedPublisher, fpp.coston.name_to_abi("IIFtsoFeedPublisher")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIFtso, fpp.coston.name_to_abi("IIFtso"))
        self.assertIsNot(fpp.coston.abis.IIFtso, fpp.coston.name_to_abi("IIFtso"))
        for el1, el2 in zip(fpp.coston.abis.IIFtso, fpp.coston.name_to_abi("IIFtso")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIPollingFoundation, fpp.coston.name_to_abi("IIPollingFoundation"))
        self.assertIsNot(fpp.coston.abis.IIPollingFoundation, fpp.coston.name_to_abi("IIPollingFoundation"))
        for el1, el2 in zip(fpp.coston.abis.IIPollingFoundation, fpp.coston.name_to_abi("IIPollingFoundation")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIGovernorProposer, fpp.coston.name_to_abi("IIGovernorProposer"))
        self.assertIsNot(fpp.coston.abis.IIGovernorProposer, fpp.coston.name_to_abi("IIGovernorProposer"))
        for el1, el2 in zip(fpp.coston.abis.IIGovernorProposer, fpp.coston.name_to_abi("IIGovernorProposer")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.Bn256, fpp.coston.name_to_abi("Bn256"))
        self.assertIsNot(fpp.coston.abis.Bn256, fpp.coston.name_to_abi("Bn256"))
        for el1, el2 in zip(fpp.coston.abis.Bn256, fpp.coston.name_to_abi("Bn256")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIFastUpdater, fpp.coston.name_to_abi("IIFastUpdater"))
        self.assertIsNot(fpp.coston.abis.IIFastUpdater, fpp.coston.name_to_abi("IIFastUpdater"))
        for el1, el2 in zip(fpp.coston.abis.IIFastUpdater, fpp.coston.name_to_abi("IIFastUpdater")):
            self.assertIsNot(el1, el2)
        self.assertEqual(fpp.coston.abis.IIFastUpdateIncentiveManager, fpp.coston.name_to_abi("IIFastUpdateIncentiveManager"))
        self.assertIsNot(fpp.coston.abis.IIFastUpdateIncentiveManager, fpp.coston.name_to_abi("IIFastUpdateIncentiveManager"))
        for el1, el2 in zip(fpp.coston.abis.IIFastUpdateIncentiveManager, fpp.coston.name_to_abi("IIFastUpdateIncentiveManager")):
            self.assertIsNot(el1, el2)
